[package]
name = "chat-files-s3"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chat-core.workspace = true
chat-store.workspace = true

tokio.workspace = true
async-trait.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true

rust-s3 = { version = "0.38", default-features = false, features = ["tokio-rustls-tls"] }
